package dev.alexisok.untitledbot.modules.moderation.logging;

/**
 * This defines log types to be used by {@link AddRemoveLogTypes}.
 * 
 * @author AlexIsOK
 * @since 0.0.1
 */
public enum LogTypes {
    
    MESSAGE_DELETE, MESSAGE_EDIT, MESSAGE_UPDATE_GENERIC,
    
    USER_AVATAR_UPDATE, USER_TAG_UPDATE, USER_NAME_UPDATE, USER_NICKNAME_UPDATE, USER_ROLE_UPDATE, USER_UPDATE_GENERIC,
    USER_JOIN, USER_LEAVE, USER_BANNED, USER_UNBANNED, USER_MUTED, USER_UNMUTED,
    
    VOICE_CHANNEL_JOIN, VOICE_CHANNEL_LEAVE, VOICE_CHANNEL_SWITCH,
    
    SERVER_MODIFY_GENERIC,
    
    EMOJI_ADD, EMOJI_UPDATE, EMOJI_DELETE,
    
    ROLE_ADD, ROLE_UPDATE, ROLE_DELETE,
    
    CHANNEL_CREATE, CHANNEL_UPDATE, CHANNEL_DELETE
    
}
