# https://github.com/einaregilsson/build-number

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate build number
        uses: einaregilsson/build-number@v2
        with:
          token: ${{secrets.github_token}}
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"
        # Or, if you're on Windows: echo "Build number is ${env:BUILD_NUMBER}"
